# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "autonew" do |autonew|
    autonew.vm.box = "ubuntu/xenial64"
    autonew.vm.hostname = 'autonew'
    autonew.vm.box_url = "ubuntu/xenial64"

    autonew.vm.network :private_network, ip: "192.168.56.105"

    autonew.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 2048
      v.cpus = 2
      v.customize ["modifyvm", :id, "--name", "autonew"]
    end
  end
end
